# Generated by Django 5.1.1 on 2024-09-19 00:33

import apps.core.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprojects',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=apps.core.models.generate_unique_filename),
        ),
    ]
